/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poka.app.panel;

import com.poka.app.util.FileUploadMonitor;
import com.poka.app.impl.LoginActionI;
import com.poka.app.frame.PokaMainFrame;
import com.poka.entity.MoneyData;
import com.poka.entity.PokaFsn;
import com.poka.entity.PokaFsnBody;
import com.poka.printer.com.ComClient;
import com.poka.util.PostekUtil;
import com.poka.util.BundleDeal;
import com.poka.util.IOUtil;
import com.poka.util.LogManager;
import com.poka.util.StaticVar;
import com.poka.util.UploadFtp;
import com.poka.util.XmlSax;
import com.poka.util.argPro;
import gnu.io.CommPortIdentifier;
import java.awt.Color;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author poka
 */
public class GuangDianQFJJPanel extends javax.swing.JPanel implements LoginActionI {

    static final Logger logger = LogManager.getLogger(GuangDianQFJJPanel.class);
    private static final String GUANGDIANDIR = "GUANGDIANFILE";

    /**
     * Creates new form GuanZiHaoDealJPanel
     */
    public GuangDianQFJJPanel() {
        initComponents();

        this.xml = XmlSax.getInstance();
        if(XmlSax.getInstance().getDiaoChaoLogin().equals("1")){
            userjLabel.setVisible(false);
        }
        

        itemFlag = false;
        CommPortIdentifier portId = null;
        Enumeration portIdentifier = ComClient.getSerialPorts();
        while (portIdentifier.hasMoreElements()) {
            portId = (CommPortIdentifier) portIdentifier.nextElement();
            if (portId.getPortType() == CommPortIdentifier.PORT_SERIAL) {
                this.comComboBox.addItem(portId.getName());
            }
        }
        String name = this.xml.getBnakName();
        if (name != null) {
            this.bankNamejTextField.setText(name);
        }

        String sItem = this.xml.getLastCom().trim();
        this.comComboBox.setEditable(false);
        if (sItem != null) {
            this.comComboBox.setSelectedItem(sItem);
        }
        String paper = this.xml.getLastPaperSize().trim();
        this.lastPaperSizeComboBox.setEditable(false);
        if (paper != null) {
            this.lastPaperSizeComboBox.setSelectedItem(paper);
        }
        itemFlag = true;

        //this.scannerFilejButton.setEnabled(false);     
        this.guanZiHaojProgressBar.setVisible(false);
        this.guanZiHaojProgressBar.setValue(0);
        this.guanZiHaojProgressBar.setOrientation(JProgressBar.HORIZONTAL);
        this.guanZiHaojProgressBar.setStringPainted(true);
        this.guanZiHaojProgressBar.setBorderPainted(true);
        this.guanZiHaojProgressBar.setBackground(Color.pink);
        File backDir = new File(fsnbackPath);
        if (!backDir.exists()) {
            backDir.mkdirs();
        }

     //   IOUtil.deleteGuangdianFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showjLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        scannerFilejButton = new javax.swing.JButton();
        monlist = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        fileNumjLabel = new javax.swing.JLabel();
        startDealjButton = new javax.swing.JButton();
        promptjLabel = new javax.swing.JLabel();
        clearDataButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        qingdianyuanjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        shenheyuanjTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        testButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bankNamejTextField = new javax.swing.JTextField();
        lastPaperSizeComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        bachoice1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        guanZiHaojProgressBar = new com.poka.app.util.FileUploadMonitor();
        ;
        jPanel4 = new javax.swing.JPanel();
        userjLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        userLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 590));
        setMinimumSize(new java.awt.Dimension(900, 590));
        setPreferredSize(new java.awt.Dimension(900, 590));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("广电清分机处理"));
        jPanel1.setMaximumSize(new java.awt.Dimension(860, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 550));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        scannerFilejButton.setText("扫描文件");
        scannerFilejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scannerFilejButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("本地文件个数:");

        fileNumjLabel.setText("0");

        startDealjButton.setText("处理文件");
        startDealjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startDealjButtonMouseClicked(evt);
            }
        });

        clearDataButton.setText("初始化数据");
        clearDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearDataButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monlist, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scannerFilejButton)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileNumjLabel)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(promptjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(startDealjButton)
                                .addGap(41, 41, 41)
                                .addComponent(clearDataButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scannerFilejButton)
                    .addComponent(startDealjButton)
                    .addComponent(clearDataButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(fileNumjLabel))
                    .addComponent(promptjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monlist, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("清点员:");

        jLabel6.setText("审核员:");

        jLabel13.setText("每捆把数:");

        comComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comComboBoxItemStateChanged(evt);
            }
        });

        jLabel10.setText("打印机COM口:");

        testButton.setText("打印机测试");
        testButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("银行名称:");

        lastPaperSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "155*77", "100*50" }));
        lastPaperSizeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lastPaperSizeComboBoxItemStateChanged(evt);
            }
        });

        jLabel14.setText("封签尺寸:");

        bachoice1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "5" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qingdianyuanjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shenheyuanjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bachoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(4, 4, 4)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bankNamejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastPaperSizeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 121, Short.MAX_VALUE)))
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qingdianyuanjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(shenheyuanjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bachoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lastPaperSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(testButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        jLabel4.setText("* 如果在处理的时候,速度比较缓慢,可能是前置机的配置不正确。");

        userjLabel.setText("当前用户：");

        logoutButton.setText("退出登录");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(userjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(userLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(userLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guanZiHaojProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guanZiHaojProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(936, 936, 936)
                .addComponent(showjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        if (isRun) {
            JOptionPane.showMessageDialog(null, "程序正在处理,请等待处理完成,再退出.");
            return;
        }
        if (pokaMain.login) {
            pokaMain.login = false;
            this.pokaMain.atmMenu.setEnabled(true);
            this.pokaMain.fileChangeMenu.setEnabled(true);
            this.pokaMain.dealGuanZiHaojMenu.setEnabled(true);
            this.pokaMain.chenbo.removeAll();
            this.pokaMain.chenbo.repaint();
            this.pokaMain.getGuangdianMenu().setEnabled(true);
            this.xml.setBnakName(this.bankNamejTextField.getText().trim());
        }
    }//GEN-LAST:event_logoutButtonMouseClicked

//    private int checkUser() {
//        String user = this.qingdianyuanjTextField.getText().trim();
//        String checker = this.shenheyuanjTextField.getText().trim();
//
//        BaseDao<Map> b = new BaseDao<Map>();
//        String sql = "select"
//                + " USERCODE"
//                + " from"
//                + " USERINFO"
//                + " where"
//                + " USERNAME=:user";
//        Map<String, Object> map = new HashMap<String, Object>();
//        map.put("user", user);
//
//        List<Map> u = null;
//        try {
//            u = b.findBySql(sql, map);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "数据库连接错误，请检查数据库配置是否正确。");
//            return -1;
//        }
//
//        for (Map map1 : u) {
//            userCode = map1.get("USERCODE").toString();
//        }
//        if (u == null || u.size() == 0) {
//            return 1;
//        }
//
//        map.clear();
//        map.put("user", checker);
//
//        u = null;
//        try {
//            u = b.findBySql(sql, map);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "数据库连接错误，请检查数据库配置是否正确。");
//        }
//        for (Map map1 : u) {
//            checkerCode = map1.get("USERCODE").toString();
//        }
//        if (u == null || u.size() == 0) {
//            return 2;
//        }
//        return 0;
//    }
    String userCode = "";
    String checkerCode = "";

    /**
     * 扫描文件
     *
     * @param evt
     */
    private void scannerFilejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scannerFilejButtonMouseClicked
        this.monlist.clear();
        this.promptjLabel.setText("");
        //JOptionPane.showMessageDialog(null, this.pokaMain.getLoginUser());
        File guangDianDir = new File(guangDianPath);
        if (!guangDianDir.exists()) {
            guangDianDir.mkdirs();
            return;
        }
        //过滤fsn
        guangDianFiles = guangDianDir.listFiles(new FileFilter() {
            public boolean accept(File file) {
                return file.getName().endsWith(".FSN");
            }
        });
        this.fileNumjLabel.setText(String.valueOf(guangDianFiles.length));
        filesCount = guangDianFiles.length;
        for (int i = 0; i < filesCount; i++) {
            File mfile = guangDianFiles[i];
            String file = mfile.getName();
            String oldFilePath = guangDianPath + File.separator + file;
            File oldFile = new File(oldFilePath);
            String newFilePath = guangDianPath + File.separator + file + ".NICE";
            File newFile = new File(newFilePath);
            if (oldFile.renameTo(newFile)) {
                if (newFile.renameTo(oldFile)) {
                    this.monlist.add(file);
                }
            }
        }
    }//GEN-LAST:event_scannerFilejButtonMouseClicked

    private String usercode = "";
    private void startDealjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startDealjButtonMouseClicked
        inventory = this.qingdianyuanjTextField.getText().trim();
        auditer = this.shenheyuanjTextField.getText().trim();
        if ("".equals(inventory)) {
            JOptionPane.showMessageDialog(null, "清点员为空.");
            this.qingdianyuanjTextField.requestFocus();
            return;
        }
        if ("".equals(auditer)) {
            JOptionPane.showMessageDialog(null, "复核员为空.");
            this.shenheyuanjTextField.requestFocus();
            return;
        }

//        int iRet = checkUser();
//        if (iRet == -1 || iRet == 1) {
//            JOptionPane.showMessageDialog(null, "请输入正确的清点员和审核员！");
//            this.qingdianyuanjTextField.selectAll();
//            return;
//        } else if (iRet == 2) {
//            JOptionPane.showMessageDialog(null, "请输入正确的审核员！");
//            this.shenheyuanjTextField.selectAll();
//            return;
//        }
        if (this.monlist.getItemCount() < 10) {
            this.promptjLabel.setText("FSN文件数量少于10个,暂时不处理");
            return;
        }
        if (this.bankNamejTextField.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "银行名称为空.");
            this.bankNamejTextField.requestFocus();
            return;
        }

        this.bankName = this.bankNamejTextField.getText().trim();
        bashu = Integer.parseInt(bachoice1.getSelectedItem().toString().trim());
//        args = new String[4 + bashu];
//        Map<String, Object> myArg = new HashMap<String, Object>();
//        myArg.put("baCount", bashu);
//        BaseDao<Map> b = new BaseDao<Map>();
//        String sql = "select GetMoneyId(100,:baCount) from DUAL";  //从数据库获取卷别
//        String result = b.getFunc(sql, myArg);
//        juanbie = result;  //将获取到的值赋给变量
        args[2] = this.userCode;
        args[3] = this.checkerCode;
        this.clearDataButton.setEnabled(false);
        this.bachoice1.setEnabled(false);
        Thread tt = new Thread(new Runnable() {
            public void run() {
                scannerMoneyData();
            }
        ;
        });
         tt.start();

    }//GEN-LAST:event_startDealjButtonMouseClicked

    private void promptjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promptjLabelMouseClicked

    }//GEN-LAST:event_promptjLabelMouseClicked

    /**
     * 清除文件夹中的fsn文件
     *
     * @param evt
     */
    private void clearDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDataButtonMouseClicked
        Object[] options = {"确定", "取消"};
        int response = JOptionPane.showOptionDialog(this, "确定清除文件夹中所有数据", "提示", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (response == 0) {
            //删除广电清分机后台文件      
        //    IOUtil.deleteGuangdianFile();
            monlist.clear();
            this.fileNumjLabel.setText("0");
            JOptionPane.showMessageDialog(null, "文件清除完成");
        }

    }//GEN-LAST:event_clearDataButtonMouseClicked

    private XmlSax xml;
    private boolean itemFlag = false;
    private void comComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comComboBoxItemStateChanged
        if (itemFlag) {
            String com = (String) this.comComboBox.getSelectedItem();
            this.xml.setLastCom(com);
        }
    }//GEN-LAST:event_comComboBoxItemStateChanged

    private void testButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testButtonMouseClicked
        PostekUtil post = new PostekUtil();
        String com = (String) this.comComboBox.getSelectedItem();
        int paper = this.lastPaperSizeComboBox.getSelectedIndex();
        if (0 == paper) {
            post.printWZ(com, "2014-10-24", "测试员一", "100", "测试员二", "123456789012345678901234", "打印测试", 10);
        } else {
            post.printGX100X50(com, "2014-10-24", "测试员一", "100", "测试员二", "123456789012345678901234", "打印测试", 10);
        }
    }//GEN-LAST:event_testButtonMouseClicked

    private void lastPaperSizeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lastPaperSizeComboBoxItemStateChanged
        if (itemFlag) {
            String paper = (String) this.lastPaperSizeComboBox.getSelectedItem();
            this.xml.setLastPaperSize(paper);
        }
    }//GEN-LAST:event_lastPaperSizeComboBoxItemStateChanged

    private void scannerMoneyData() {
        String monVal = "";
        guanZiHaojProgressBar.setValue(0);
        guanZiHaojProgressBar.setOrientation(JProgressBar.HORIZONTAL);
        guanZiHaojProgressBar.setStringPainted(true);
        guanZiHaojProgressBar.setBorderPainted(true);
        guanZiHaojProgressBar.setBackground(Color.pink);
        guanZiHaojProgressBar.setVisible(true);
        guanZiHaojProgressBar.setMaximum(10);
        guanZiHaojProgressBar.setToolTipText("正在转化文件......");
        count = 0;
        String[] aviFiles = this.monlist.getItems();
        isRun = true;  //标示是否在运行中
        for (int i = 0; i < aviFiles.length; i++) {
            String mfile = aviFiles[i];
            String filePath = guangDianPath + File.separator + mfile;
            PokaFsn temR = new PokaFsn();
            try {
                temR.readBaseFsnFile(filePath);   //读取FSN文件信息
            } catch (IOException ex) {
               logger.log(Level.INFO, null,ex);
            }
            List<PokaFsnBody> bd = temR.getbList();
            if (bd.size() != 100) {
                isRightNum = false;
                Object[] options = {"忽略", "退出"};
                int response = JOptionPane.showOptionDialog(this, filePath + "文件冠字号个数不为100条,不满足执行条件", "提示", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                if (response == 0) {

                    continue;
                } else if (response == 1) {
                    isRun = false;
                    this.guanZiHaojProgressBar.setVisible(false);
                    return;
                }

            } else {
                String baId = IOUtil.getBaID() + count;
                for (PokaFsnBody mybd : bd) {
                    mybd.setUserId1(args[2]);
                    mybd.setUserId2(args[3]);
                    mybd.setFlag((byte) 0);
                    monVal = "" + mybd.getValuta();
                    pokaFsn.add(mybd);
                    // pokaFsn.getFhead().setCount(pokaFsn.getFhead().getCount() + 1);
                }
                guanZiHaojProgressBar.setValue(guanZiHaojProgressBar.getValue() + 1);
                pokaFsn.addBundleId(baId);
                args[count + 4] = baId;
                count++;
                this.removeFileList.add(new File(filePath));
            }
            if (count == bashu) {
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                   logger.log(Level.INFO, null,ex);
                }
                Date date = BundleDeal.getDBTime();
                //捆ID           
                //生成捆ID     
                if (this.xml.getDiaoChaoLogin().equals("1")) {
                    StaticVar.loginUser = qingdianyuanjTextField.getText();
                }
                
                juanbie = this.xml.getQuans(monVal, "" + bashu);
                
                String kunID = BundleDeal.productBKbunId(StaticVar.loginUser, juanbie, 1);
                //生成fsn
                String fsnFileName = StaticVar.bankId + "_" + StaticVar.agencyNo + "_XXXXXXXXXXXXXX_" + kunID + ".FSN";
                String mypath = StaticVar.cfgMap.get(argPro.localAddr) + File.separator + UploadFtp.tem + File.separator + fsnFileName;
                try {
                    pokaFsn.writePokaFsnFile(mypath);
                    pokaFsn = new PokaFsn();
                } catch (Exception ex) {
                   logger.log(Level.INFO, null,ex);
                }
                args[0] = kunID;
                args[1] = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").format(date);
                //生成bk文件
                String fileName = StaticVar.bankId + "_" + StaticVar.agencyNo + "_XXXXXXXXXXXXXX_" + kunID + (bashu == 5 ? "_05" : "") + ".BK";
                String BKNamePath = StaticVar.cfgMap.get(argPro.localAddr) + File.separator + UploadFtp.tem + File.separator + fileName;
                IOUtil.writeBKFile(args, BKNamePath);   //生成bk文件                                      
                filesCount = filesCount - removeFileList.size();
                this.fileNumjLabel.setText(String.valueOf((filesCount)));
                //备份处理过的文件

                for (File f : removeFileList) {
                    if (f.exists()) {
                        File backFile = new File(fsnbackPath + f.getName());
                        if (backFile.exists()) {
                            backFile = new File(fsnbackPath + f.getName() + "." + (new SimpleDateFormat("yyyyMMddHHmmssSSS")).format(BundleDeal.getDBTime()));
                        }
                        f.renameTo(backFile);
                    }
                    this.monlist.remove(f.getName());
                }
                guanZiHaojProgressBar.setValue(0);
                //上传BK文件
                UploadFtp.oneFileUploadFtp(fileName, UploadFtp.bkbak, (FileUploadMonitor) guanZiHaojProgressBar);
                //上传FSN文件
                UploadFtp.oneFileUploadFtp(fsnFileName, UploadFtp.fsnbak);

                //打印捆封签
                PostekUtil post = new PostekUtil();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                String printDate = sdf.format(date);

                String com = (String) this.comComboBox.getSelectedItem();

                post.printWZ(com, printDate, auditer, monVal, inventory, kunID, bankName, bashu);

                int paper = this.lastPaperSizeComboBox.getSelectedIndex();
                if (0 == paper) {
                    post.printWZ(com, printDate, auditer, monVal, inventory, kunID, bankName, bashu);
                } else {
                    post.printGX100X50(com, printDate, auditer, monVal, inventory, kunID, bankName, bashu);
                }

                count = 0;
                removeFileList.clear();
                guanZiHaojProgressBar.setValue(0);
            }

        }
        guanZiHaojProgressBar.setVisible(false);
        if (isRightNum) {
            JOptionPane.showMessageDialog(null, "处理完成.");
        }
        isRun = false;
        this.clearDataButton.setEnabled(true);
        this.bachoice1.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bachoice1;
    private javax.swing.JTextField bankNamejTextField;
    private javax.swing.JButton clearDataButton;
    private javax.swing.JComboBox comComboBox;
    private javax.swing.JLabel fileNumjLabel;
    private javax.swing.JProgressBar guanZiHaojProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox lastPaperSizeComboBox;
    private javax.swing.JButton logoutButton;
    private java.awt.List monlist;
    private javax.swing.JLabel promptjLabel;
    private javax.swing.JTextField qingdianyuanjTextField;
    private javax.swing.JButton scannerFilejButton;
    private javax.swing.JTextField shenheyuanjTextField;
    private javax.swing.JLabel showjLabel;
    private javax.swing.JButton startDealjButton;
    private javax.swing.JButton testButton;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel userjLabel;
    // End of variables declaration//GEN-END:variables
    private List<String> BkList = new ArrayList<String>();
    private List<MoneyData> myList = new ArrayList<MoneyData>();
    private int count = 0;

    private PokaFsn pokaFsn = new PokaFsn();
    private String[] args = new String[14];
    private String inventory;  //清点员
    private String auditer;   //审核员
    private String jiju;     //机具
    private String juanbie = ""; //劵别
    private String bankName; //银行名称   
    private PokaMainFrame pokaMain;
    private List<File> removeFileList = new ArrayList<File>();
    private File[] guangDianFiles;
    private String guangDianPath = StaticVar.cfgMap.get(argPro.localAddr) + File.separator + GUANGDIANDIR;
    private String fsnbackPath = StaticVar.cfgMap.get(argPro.localAddr) + File.separator + UploadFtp.basebak + File.separator;
    private boolean isRun = false;
    private int filesCount = 0;
    private boolean isRightNum = true; //fsn是否满足100条
    private int bashu = 0; //生成文件把数

    @Override
    public void initLogin() {
      //  this.pokaMain.fileChangeMenu.setEnabled(false);
        this.pokaMain.atmMenu.setEnabled(false);
        this.pokaMain.dealGuanZiHaojMenu.setEnabled(false);
        this.userLabel1.setText(StaticVar.loginName);
        this.qingdianyuanjTextField.setText(this.pokaMain.getLoginUserName());
        if (this.pokaMain.getLoginUser().length() <= 0) {
            this.qingdianyuanjTextField.setEditable(true);
        } else {
            this.qingdianyuanjTextField.setEditable(false);
        }
        this.shenheyuanjTextField.setText(this.pokaMain.getCheckUserName());
        if (this.pokaMain.getCheckUser().length() <= 0) {
            this.shenheyuanjTextField.setEditable(true);
        } else {
            this.shenheyuanjTextField.setEditable(false);
        }
    }

    /**
     * @param pokaMain the pokaMain to set
     */
    public void setPokaMain(PokaMainFrame pokaMain) {
        this.pokaMain = pokaMain;
    }
}
