/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poka.app.frame;

import com.poka.app.panel.DataSendJPanel;
import com.poka.util.LogManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class DataSendFrame extends javax.swing.JFrame {

    private PokaMainFrame pokaMain;

    static final Logger logger = LogManager.getLogger(DataSendFrame.class);
    /**
     * Creates new form DataSendFrame
     */
    public DataSendFrame() {
        initComponents();
        this.setResizable(false);
        
      //  this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.pack();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        ImageIcon a = new ImageIcon(getClass().getResource("/com/poka/images/2.png"));

        this.setIconImage(a.getImage());
        this.setTitle("点钞机数据采集");
        pan = new DataSendJPanel();
        pan.getLogoutButton().setVisible(false);
        intiWindoes();
        
    }
    private DataSendJPanel pan;

    public void addPanel(JPanel pan) {
        Toolkit kit = Toolkit.getDefaultToolkit(); // 定义工具包    
        Dimension screenSize = kit.getScreenSize(); // 获取屏幕的尺寸   
        double screenWidth = screenSize.width; // 获取屏幕的宽   
        double screenHeight = screenSize.height; // 获取屏幕的高    

        this.mainPanel.removeAll();
        javax.swing.GroupLayout chenboLayout = new javax.swing.GroupLayout(this.mainPanel);
        this.mainPanel.setLayout(chenboLayout);

        int tem = (int) pan.getPreferredSize().getWidth();
        GroupLayout.SequentialGroup hGroup = chenboLayout.createSequentialGroup();
        if (screenWidth > pan.getPreferredSize().getWidth()) {
            hGroup.addGap((int) ((screenWidth - pan.getPreferredSize().getWidth()) / 2));
            pan.setSize(pan.getPreferredSize());
        } else {
            pan.setMaximumSize(this.getPreferredSize());
            pan.setSize(screenSize);
        }
        hGroup.addComponent(pan);
        chenboLayout.setHorizontalGroup(hGroup);
        GroupLayout.SequentialGroup vGroup = chenboLayout.createSequentialGroup();
        vGroup.addGap(15);
        vGroup.addComponent(pan);
        chenboLayout.setVerticalGroup(vGroup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int i = JOptionPane.showConfirmDialog(null, "确定要退出点钞机数据采集吗？", "退出数据采集", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            if (this.pokaMain != null) {
                this.pokaMain.setDataSendFram(null);
            }
            if (pan.getfServer() != null) {
                pan.getfServer().stop();
            }
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           this.dispose();
           
        }

    }//GEN-LAST:event_formWindowClosing
    public void intiWindoes(){
        this.mainPanel.removeAll();
            javax.swing.GroupLayout chenboLayout = new javax.swing.GroupLayout(this.mainPanel);
            this.mainPanel.setLayout(chenboLayout);

            int tem = (int) pan.getPreferredSize().getWidth();
            GroupLayout.SequentialGroup hGroup = chenboLayout.createSequentialGroup();

            hGroup.addGap(0);
            pan.setSize(pan.getPreferredSize());

            hGroup.addComponent(pan);
            chenboLayout.setHorizontalGroup(hGroup);
            GroupLayout.SequentialGroup vGroup = chenboLayout.createSequentialGroup();
            vGroup.addGap(15);
            vGroup.addComponent(pan);
            chenboLayout.setVerticalGroup(vGroup);

            int windowWidth = pan.getWidth();
            int windowHeight = pan.getHeight();
            Toolkit kit = Toolkit.getDefaultToolkit(); // 定义工具包    
            Dimension screenSize = kit.getScreenSize(); // 获取屏幕的尺寸   
            int screenWidth = screenSize.width; // 获取屏幕的宽   
            int screenHeight = screenSize.height; // 获取屏幕的高    
            //System.out.print(screenWidth);
            this.setBounds((screenWidth - windowWidth) / 2, 0, windowWidth + 10, windowHeight + 30);
    }
    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        if (evt.getNewState() == 0) {
            

        } else if (evt.getNewState() == 6) {
            this.addPanel(pan);
        }
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.INFO, null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSendFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the pokaMain
     */
    public PokaMainFrame getPokaMain() {
        return pokaMain;
    }

    /**
     * @param pokaMain the pokaMain to set
     */
    public void setPokaMain(PokaMainFrame pokaMain) {
        this.pokaMain = pokaMain;
    }
}
