/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poka.app.frame;

import com.poka.util.RegistrationUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.border.StandardBorderPainter;
import org.jvnet.substance.button.StandardButtonShaper;
import org.jvnet.substance.painter.StandardGradientPainter;
import org.jvnet.substance.skin.SubstanceCremeCoffeeLookAndFeel;
import org.jvnet.substance.theme.SubstanceSteelBlueTheme;
import org.jvnet.substance.title.Glass3DTitlePainter;
import org.jvnet.substance.watermark.SubstanceBubblesWatermark;

/**
 *
 * @author Administrator
 */
public class PokaRegister extends javax.swing.JFrame {

    
    /**
     * Creates new form PokaRegistration
     */
    public PokaRegister() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit(); // 定义工具包    
        Dimension screenSize = kit.getScreenSize(); // 获取屏幕的尺寸   
        int screenWidth = screenSize.width; // 获取屏幕的宽   
        int screenHeight = screenSize.height; // 获取屏幕的高    
        System.out.print(screenWidth);
        this.setBounds((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2, 600, 350);
        this.reButton.setEnabled(true);
        this.maTextField.setEditable(true);
        this.reTextField.setEditable(false);
        this.setTitle("冠字号采集软件注册机");
        //this.maTextField.setText("hdgjun");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maTextField = new javax.swing.JTextField();
        reTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maButton = new javax.swing.JButton();
        reButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maTextField.setEditable(false);
        maTextField.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        reTextField.setEditable(false);
        reTextField.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        jLabel1.setText("机器码：");

        jLabel2.setText("注册码：");

        maButton.setText("机器码");
        maButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maButtonMouseClicked(evt);
            }
        });

        reButton.setText("注册码");
        reButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(maTextField)
                                .addComponent(reTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(maButton)
                        .addGap(120, 120, 120)
                        .addComponent(reButton)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maButtonMouseClicked
        this.reButton.setEnabled(true);
        StringBuilder sTem = new StringBuilder();
        mCode = RegistrationUtil.getMachineCode().toUpperCase().trim();
        int i = 0;
        for (char c : mCode.toCharArray()) {
            sTem.append(c);
            i++;
            if (i % 4 == 0) {
                sTem.append("-");
            }
        }
        String tx = sTem.toString();
        if (tx.endsWith("-")) {
            tx = tx.substring(0, tx.length() - 1);
        }
        maTextField.setText(tx);
    }//GEN-LAST:event_maButtonMouseClicked

    private void reButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reButtonMouseClicked

        mCode = maTextField.getText().toUpperCase().trim().replaceAll("-", "");
        if(mCode.length()<=0){
            return;
        }
        rCode = RegistrationUtil.getRegistration(mCode);
        StringBuilder sTem = new StringBuilder();

        int i = 0;
        for (char c : rCode.toCharArray()) {
            sTem.append(c);
            i++;
            if (i % 4 == 0) {
                sTem.append("-");
            }
        }
        String tx = sTem.toString();
        if (tx.endsWith("-")) {
            tx = tx.substring(0, tx.length() - 1);
        }
        reTextField.setText(tx);
    }//GEN-LAST:event_reButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokaRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JFrame.setDefaultLookAndFeelDecorated(true);
                    JDialog.setDefaultLookAndFeelDecorated(true);
//         //设置外观  

                    UIManager.setLookAndFeel(new SubstanceCremeCoffeeLookAndFeel());
//            UIManager.setLookAndFeel(new SubstanceNebulaBrickWallLookAndFeel());
                    //设置主题   
                    SubstanceLookAndFeel.setCurrentTheme(new SubstanceSteelBlueTheme());
                    //设置按钮外观  
                    SubstanceLookAndFeel.setCurrentButtonShaper(new StandardButtonShaper());
                    //设置水印  
                    SubstanceLookAndFeel.setCurrentWatermark(new SubstanceBubblesWatermark());
                    //设置边框  
                    SubstanceLookAndFeel.setCurrentBorderPainter(new StandardBorderPainter());
                    //设置渐变渲染  
                    SubstanceLookAndFeel.setCurrentGradientPainter(new StandardGradientPainter());
                    //设置标题  
                    SubstanceLookAndFeel.setCurrentTitlePainter(new Glass3DTitlePainter());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new PokaRegister().setVisible(true);
            }
        });
    }

    private String mCode = "";
    private String rCode = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton maButton;
    private javax.swing.JTextField maTextField;
    private javax.swing.JButton reButton;
    private javax.swing.JTextField reTextField;
    // End of variables declaration//GEN-END:variables
}
